/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.CandidatoDTO;

/**
 *
 * @author aleja
 */
public class UsuarioInscripcion extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioInscripcion
     */
    public UsuarioInscripcion() {
        initComponents();
        this.setLocationRelativeTo(null);// Centra la pantalla
        panelSegundario.setVisible(false);
        panelTerciario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPricipal = new javax.swing.JPanel();
        botonCrearCandidato = new javax.swing.JButton();
        botonConsultarCandidato = new javax.swing.JButton();
        botonActualizarCandidato = new javax.swing.JButton();
        panelSegundario = new javax.swing.JPanel();
        textoNumeroCandidato = new javax.swing.JTextField();
        textoCedula = new javax.swing.JTextField();
        textoFechaInscripcion = new javax.swing.JTextField();
        textoIdProceso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        panelTerciario = new javax.swing.JPanel();
        botonConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textoNumeroCandidatoConsulta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonCrearCandidato.setText("Crear Candidato");
        botonCrearCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCandidatoActionPerformed(evt);
            }
        });

        botonConsultarCandidato.setText("Consultar Candidato");
        botonConsultarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarCandidatoActionPerformed(evt);
            }
        });

        botonActualizarCandidato.setText("ActualizarCandidato");
        botonActualizarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarCandidatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Candidato");

        jLabel2.setText("Cedula");

        jLabel3.setText("Fecha Inscripcion");

        jLabel4.setText("ID Proceso Electoral");

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        jLabel7.setText("Informacion");

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSegundarioLayout = new javax.swing.GroupLayout(panelSegundario);
        panelSegundario.setLayout(panelSegundarioLayout);
        panelSegundarioLayout.setHorizontalGroup(
            panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSegundarioLayout.createSequentialGroup()
                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSegundarioLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel7))
                    .addGroup(panelSegundarioLayout.createSequentialGroup()
                        .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSegundarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textoIdProceso)
                                    .addComponent(textoFechaInscripcion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoNumeroCandidato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                            .addGroup(panelSegundarioLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(botonCrear)))
                        .addGap(18, 18, 18)
                        .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonActualizar)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelSegundarioLayout.setVerticalGroup(
            panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSegundarioLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNumeroCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoIdProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrear)
                    .addComponent(botonActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        jLabel5.setText("Consultar");

        jLabel6.setText("Numero Candidato");

        javax.swing.GroupLayout panelTerciarioLayout = new javax.swing.GroupLayout(panelTerciario);
        panelTerciario.setLayout(panelTerciarioLayout);
        panelTerciarioLayout.setHorizontalGroup(
            panelTerciarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTerciarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonConsultar)
                .addGap(134, 134, 134))
            .addGroup(panelTerciarioLayout.createSequentialGroup()
                .addGroup(panelTerciarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTerciarioLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5))
                    .addGroup(panelTerciarioLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(textoNumeroCandidatoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelTerciarioLayout.setVerticalGroup(
            panelTerciarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerciarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(panelTerciarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNumeroCandidatoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(94, 94, 94)
                .addComponent(botonConsultar)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPricipalLayout = new javax.swing.GroupLayout(panelPricipal);
        panelPricipal.setLayout(panelPricipalLayout);
        panelPricipalLayout.setHorizontalGroup(
            panelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPricipalLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(botonCrearCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(botonConsultarCandidato)
                .addGap(217, 217, 217)
                .addComponent(botonActualizarCandidato)
                .addGap(90, 90, 90))
            .addGroup(panelPricipalLayout.createSequentialGroup()
                .addComponent(panelSegundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTerciario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPricipalLayout.setVerticalGroup(
            panelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPricipalLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearCandidato)
                    .addComponent(botonConsultarCandidato)
                    .addComponent(botonActualizarCandidato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTerciario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSegundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        try {
            crearInscripcion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UsuarioInscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        try {
            actualizar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UsuarioInscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        int numeroCandidato = Integer.parseInt(textoNumeroCandidato.getText());
        CandidatoDTO candidatoDTO = new CandidatoDTO(0, 0, numeroCandidato, null);
        
        List lista = new ArrayList();
        
        try {
            lista = candidatoDTO.consultarCandidato();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UsuarioInscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (lista.isEmpty()) {
            // vista no se encuentra candidato
            JOptionPane.showMessageDialog(null, "No se encuentra el candidato");
        } else {
            // vista impresion informacion
            JOptionPane.showMessageDialog(null, lista);
        }
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonCrearCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCandidatoActionPerformed
        panelSegundario.setVisible(true);
        panelTerciario.setVisible(false);
        botonActualizar.setVisible(false);
        botonCrear.setVisible(true);
    }//GEN-LAST:event_botonCrearCandidatoActionPerformed

    private void botonConsultarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarCandidatoActionPerformed
        panelSegundario.setVisible(true);
        panelTerciario.setVisible(true);
        botonActualizar.setVisible(false);
        botonCrear.setVisible(false);
    }//GEN-LAST:event_botonConsultarCandidatoActionPerformed

    private void botonActualizarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarCandidatoActionPerformed
        panelSegundario.setVisible(true);
        panelTerciario.setVisible(false);
        botonActualizar.setVisible(true);
        botonCrear.setVisible(false);
    }//GEN-LAST:event_botonActualizarCandidatoActionPerformed

   

    public void crearInscripcion() throws ClassNotFoundException {
        int cedula = Integer.parseInt(textoCedula.getText());
        int idProceso = Integer.parseInt(textoIdProceso.getText());
        int numeroCandidato = Integer.parseInt(textoNumeroCandidato.getText());
        java.sql.Timestamp fechaInscripcion = java.sql.Timestamp.valueOf(textoFechaInscripcion.getText());

        CandidatoDTO candidatoDTO = new CandidatoDTO(cedula, idProceso, numeroCandidato, fechaInscripcion);

        String mensaje;
        mensaje = candidatoDTO.crearCandidato();
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public void actualizar() throws ClassNotFoundException {
        int cedula = Integer.parseInt(textoCedula.getText());
        int idProceso = Integer.parseInt(textoIdProceso.getText());
        int numeroCandidato = Integer.parseInt(textoNumeroCandidato.getText());
        java.sql.Timestamp fechaInscripcion = java.sql.Timestamp.valueOf(textoFechaInscripcion.getText());

        CandidatoDTO candidatoDTO = new CandidatoDTO(cedula, idProceso, numeroCandidato, fechaInscripcion);

        String mensaje;
        mensaje = candidatoDTO.actualizarCandidato();
        JOptionPane.showMessageDialog(null, mensaje);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonActualizarCandidato;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonConsultarCandidato;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonCrearCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelPricipal;
    private javax.swing.JPanel panelSegundario;
    private javax.swing.JPanel panelTerciario;
    private javax.swing.JTextField textoCedula;
    private javax.swing.JTextField textoFechaInscripcion;
    private javax.swing.JTextField textoIdProceso;
    private javax.swing.JTextField textoNumeroCandidato;
    private javax.swing.JTextField textoNumeroCandidatoConsulta;
    // End of variables declaration//GEN-END:variables
}
